version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgresql-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - postgresql-network
    volumes:
      - postgresql-postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgresql-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    networks:
      - postgresql-network
    volumes:
      - postgresql-pgadmin:/var/lib/pgadmin
volumes:
  postgresql-postgres:
  postgresql-pgadmin:
networks:
  postgresql-network:
